# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Getopt-Compact
version:      0.03
version_from: lib/Getopt/Compact.pm
installdirs:  site
requires:
    Carp:                          0
    Env::Path:                     0
    File::Basename:                0
    File::Spec:                    0
    Getopt::Long:                  0
    Pod::Parser:                   0
    Pod::Simple::Text::Termcap:    0
    Text::Table:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
